### ISSUE TITLE
Feature request - Ramen

### ISSUE THREAD

**Issue by Icosahunter** [DerpyNinjaFrog/world-of-food#4]
Crafted with wheat, cooked fish, dried kelp, and bowl. I would say water too, but that wouldn't be consistent with existing Minecraft soup recipes. Alternatively to cooked fish you could have raw fish be able to craft into multiple fish cakes and you use that in the ramen, that's probably excessive though.

**Comment by DerpyNinjaFrog** [comment]
I'll add it with the recipe wheat, cooked fish, dried kelp, and bowl.
