### ISSUE TITLE
Feature request - Mashed Potatoes and Shepherd's Pie

### ISSUE THREAD

**Issue by Icosahunter** [DerpyNinjaFrog/world-of-food#6]
Mashed potatoes would be crafted with potato, butter and bowl. Shepherd's pie would be crafted with mashed potatoes, cooked lamb chop, carrot, and cheese. Alternatively the recipes could be seperate, and you just use a potato and bowl for shepherd's pie instead of the mashed potatoes.

**Comment by DerpyNinjaFrog** [comment]
Now 4 uses for cheese!
